#!/usr/bin/env php

<?php

/*
 * This file is part of the Terabyte yii2-extension.
 *
 * (c) Terabyte yii2-extension <http://github.com/tecnologiaterabyte>
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 *
 * @link http://www.tecnologiaterabyte.com
 * @author Wilmer Arámbula <tecnologiaterabyte@gmail.com>
 * @copyright (c) 2014 Asoc. Coop. Tecnologia Terabyte 124, RL.
 * @Extension: [yii2-adminlte].
 * @Tests App [Yii].
 * @since 1.0
 */

require __DIR__ . '/../_init.php';
require(VENDOR_DIR . '/yiisoft/yii2/Yii.php');

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = require(__DIR__ . '/config/console.php');

$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);